### ISSUE TITLE
Is it possible to configure this globally?

### ISSUE THREAD

**Issue by IceSentry** [bootandy/dust#168]
I want to be have the reverse option on by default and I'd rather not have to remember to type `-r` every time.

**Comment by bootandy** [comment]
how would that work? Are you thinking of an environment variable ?

**Comment by IceSentry** [comment]
Could be an env var, but a lot of cli tools have a config file that it then looks for at a few location.

A few examples:
https://github.com/Peltoche/lsd#configuration
https://starship.rs/config/
https://github.com/dalance/procs#configuration
https://github.com/XAMPPRocky/tokei#configuration
https://clementtsang.github.io/bottom/nightly/configuration/config-file/default-config/

**Comment by bootandy** [comment]
thanks, I'll look into this.

**Comment by xenoterracide** [comment]
`alias dust="dust -r"` and you could then use `\dust` to not use it, for posix shell only

**Comment by IceSentry** [comment]
I'm on windows, alias are a fine workaround if you can use them easily, but having a global configuration can be much easier to read than a shell command with a bunch of flags and no comments.

**Comment by xenoterracide** [comment]
I mean with Shell you can have global configurations... Unless you're trying to switch between batch, power shell and a posix shell. And obviously shell scripts at least positive shell scripts can have comments, also in shell scripts long options are generally preferred for readability and maintenance.

That said I'm not against a config file but for this particular scenario it doesn't seem like It's necessary in my mind. I noticed this when I opened an issue asking for an ignore config file, since an ignore file could be account global or directory local.

**Comment by IzhakJakov** [comment]
I would love to see this happen as well
Please make it in `$XDG_CONFIG_HOME` by default 😊 

<sup>https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html</sup>

**Comment by bootandy** [comment]
Can I get some feedback on if this is a sensible way to add config file support?

https://github.com/bootandy/dust/pull/243

thanks,

**Comment by bootandy** [comment]
Added code to do this, will go out in the next release.
