### ISSUE TITLE
Feature request: Option for auto-update

### ISSUE THREAD

**Issue by bronvic** [bootandy/dust#205]
When I need to monitor some folder size constantly, I can do it like this: `watch du --max-depth=1 -h ~/dist `
If I try the same trick with dust `dust -d1 ~/dist`, I receive... a mess in terminal
pure dust                   |  with watch
:-------------------------:|:-------------------------:
![2022-01-02_10-01-1641108212](https://user-images.githubusercontent.com/8941791/147869090-302e45cb-d6de-4949-baa8-0484acafa1e9.jpg)  |  ![2022-01-02_10-01-1641108097](https://user-images.githubusercontent.com/8941791/147869059-49b1e145-d209-4170-b883-e8fd37f5751e.jpg)

So, I thought it would be nice to have an option to make output auto-updated once in a while or on change without `watch` command!

**Comment by bootandy** [comment]
Try
`watch dust -c`
or if you have an update date watch:
`watch --color dust`

I'll add a note in help to mention watch in the help text for -c

**Comment by bronvic** [comment]
@bootandy, thank you!

**Comment by ShrirajHegde** [comment]
Hello, this works, but still seems a bit janky. Is there any plan of implementing file system monitoring so that the updates can be incremental?

Maybe an interactive mode with TUI and mouse support to enter a subdirectory like [SpaceSniffer](http://www.uderzo.it/main_products/space_sniffer/) and maybe even move items to trash. This would be a great thing, since there is no alternative of SpaceSniffer in Linux that I am aware of.

**Comment by bootandy** [comment]
Nope, 

I appreciate the feedback, but I'm trying to not add too many features into dust and I don't want to start a 'real time file system monitoring' project. I'd rather stick with 'watch  dust -c'
