### ISSUE TITLE
Running dust in ~ gives error message "Did not have permissions for all directories"

### ISSUE THREAD

**Issue by drhumlen** [bootandy/dust#210]
First time I ran dust I chose deny when it asked for permission to a bunch of directories. Now that I've used the tool for a while, I want to grant it permission to those directories, but there's no way to grant it permission now? I even tried `brew uninstall dust` and then re-installing it, but it still doesn't prompt me for permission again.

**Comment by peterjc** [comment]
Was this on macOS?

**Comment by drhumlen** [comment]
@peterjc Yes

**Comment by bootandy** [comment]
That sounds like a mac system level  problem .

Try either: 
1) Run as root: `sudo dust`. 
2) Find the permission which will be saved somewhere in mac settings and grant it.

**Comment by tjx666** [comment]
@bootandy 

<img width="525" alt="image" src="https://user-images.githubusercontent.com/41773861/207137747-4c582493-328e-4486-ae93-2f5232293310.png">

**Comment by hamzamohdzubair** [comment]
i have the same issue on linux, cannot run `sudo dust`, because dust is not installed on root

**Comment by AnkushMalaker** [comment]
@hamzamohdzubair 
You can use\
`which dust`\
from your normal user where dust is installed, and then run `sudo /home/<user>/.cargo/bin/dust`, for example. 

In my case, I still got the `Did not have permissions for all directories` error and I'm running ubuntu.

**Comment by Burnus** [comment]
I have the same issue on MacOS. Running with `sudo` produces the same error. Would be nice if dust could tell me **which** directory it has an issue with.

**Comment by bootandy** [comment]
There are often a huge number of directories that it did not have permission for. However, your point it noted I'll leave this as a todo.

**Comment by Burnus** [comment]
FWIW, my issue turned out to actually be broken permissions on some directory, not a bug in dust. Still, calling out the offending path in the error message would have made it easier to pin this down.

**Comment by MithicSpirit** [comment]
Running a command like `find . >/dev/null` can be helpful for spotting the permission error. This discards stdout so all that's left are the errors in stderr, which should all be permission errors. As for adding support for showing the permission errors directly in dust it would be nice if it was kept behind a CLI flag (and printed to stderr instead of stdout).

**Comment by Burnus** [comment]
> Running a command like `find . >/dev/null` can be helpful for spotting the permission error. This discards stdout so all that's left are the errors in stderr, which should all be permission errors. 

I know. That's basically what I ended up doing. Still, this can take a very long time on large data sets and/or slow disks and I think it's unnecessary since dust must already have identified the offending directory.

> As for adding support for showing the permission errors directly in dust it would be nice if it was kept behind a CLI flag (and printed to stderr instead of stdout).

The message is already being printed to stderr and nobody advertised for changing that. As for the feature flag, I fail to understand what advantage this would provide. Does anyone prefer the generic error message over a specific one? Would there be a significant difference in runtime performance between the two approaches once you already support it on a type system level?

**Comment by ldwSpirent** [comment]
I am running on Linux (Ubuntu) as root, and have the error on a user directory.

The problem is this: the .ssh directory - to be functional for ssh usage - is required to have permissions for owner only...  i.e. "`chmod 0755 .ssh`" or "`chmod u=rwx,go-rwx .ssh`".

In this case, the permissions are correct, root **can** read the files, but dust refuses to.

This behavior seems incorrect, inconsistent, and unpredictable (after trying a few tests) when used as root.
---
```
# id
uid=0(root) gid=0(root) groups=0(root)
```
---
```
# du -sh .ssh
24K     .ssh
# dust .ssh
Did not have permissions for all directories
 4.0K ┌── .ssh│█████████████████████████████████████████████████████████████████████████████████████████████████████████████████ │ 100%
# sudo dust .ssh
Did not have permissions for all directories
 4.0K ┌── .ssh│█████████████████████████████████████████████████████████████████████████████████████████████████████████████████ │ 100%
```
---
```
# du -sh .
4.4G    .
# dust .
Did not have permissions for all directories
 4.0K ┌── .│████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ │ 100%
```

**Comment by bootandy** [comment]
I can reproduce your issue DianaNites - I'll look at this.
