### ISSUE TITLE
Path with spaces are not recognized (Windows)

### ISSUE THREAD

**Issue by nadya-p** [bootandy/dust#225]
Typically on Windows, some paths contain spaces. Such the paths don't seem to be recognized by dust:

PS C:\> ls .\test\
-a----        07/07/2022     14:23              5 file.txt
PS C:\> ls '.\test with space\'
-a----        07/07/2022     14:23              5 file.txt

PS C:\> a .\test\
   5B   ┌── file.txt│█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ │ 100%
   5B ┌─┴ test      │█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ │ 100%

PS C:\> a ".\test with space\"
Did not have permissions for all directories

**Comment by bootandy** [comment]
I tried creating a path with a space in linux and it worked fine. Will likely need someone with a windows box to confirm and fix this.

**Comment by jeffcai** [comment]
<img width="902" alt="issue" src="https://user-images.githubusercontent.com/671273/181404437-a02baa3b-042d-4579-be1a-90063bd04b3f.png">

I did test, if the director not exits it will show the exception: Did not have permissions for all directories, otherwise even with the directory name with space it still works, the tested release is dust-v0.8.1-x86_64-pc-windows-gnu.zip on Win enterprise 10.

**Comment by lesleyrs** [comment]
Yea just like @jeffcai it works for me as long as the directory exists.

I still get the permission message when using `dust` in a system directory even with admin rights, not sure why? But it still works correctly. So I don't think there's a problem here.
