### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by GiveMeFox** [bootandy/dust#289]
just installed it with `cargo install du-dust`
![image](https://user-images.githubusercontent.com/74460065/211184402-e204aaed-c19b-48f5-982e-d95bc76bcb04.png)

**Comment by bootandy** [comment]
ok, that's interesting. 

Do you have a circular directory structure? 
Does it happen if you run dust on the /tmp directory or a smaller directory ? 
Are you running on a box with a small amount of ram ? 
Does du work ?

**Comment by bootandy** [comment]
I think this is because it is not increasing the size of your stack because it hasn't realised you have enough RAM. 

If you install the head of this repo does it fix it?

If not I'd recommend playing with the code to assign stack size in init_rayon inside main.rs see here:

https://github.com/bootandy/dust/blob/master/src/main.rs#L231

I'll push a new version soon that will have the fix in .

**Comment by bootandy** [comment]
new version is shipped did that help ?

**Comment by bootandy** [comment]
so does the new version fix it?
