### ISSUE TITLE
Is it possible to set the unit of measurement to a specified value,like KB?

### ISSUE THREAD

**Issue by TYzzt** [bootandy/dust#321]
When the size of storage is large, the accuracy loses the angle

**Comment by TYzzt** [comment]
[https://github.com/bootandy/dust/pull/322](url)

**Comment by bootandy** [comment]
I'm not particularly keen on adding this flag. What is the usecase for it? 

If you need to know the exact size of a file you can use du for that. 

dust is going to ignore several files anyway with its targetted summary so I'm not sure what value this adds.

**Comment by TYzzt** [comment]
> 

Fast and relatively accurate estimation of storage usage in HPC distributed storage scenarios

**Comment by bootandy** [comment]
Hmm, maybe, let me sleep on it.

**Comment by sergeevabc** [comment]
How do I get size in bytes? When I share files, I prefer to indicate the size in bytes so that people don't get confused by KB, KiB, etc. In addition, one can process the output in bytes later by other programs like awk and convert it into the desired units.

**Comment by christosg88** [comment]
Please add a `--format` option, to specify the output's size format.

I want to parse the output from another script (in Python in my case) to merge it with other reports.
I prefer to call `dust` in a subprocess, and parse its output, because it's much faster than a native-Python solution.
But I don't want to turn my Python script which merges reports to Rust, because it would be too much work and it's already fast enough.

Any chance to implement that?

`dua` offers this option:

```
  -f, --format <FORMAT>
          The format with which to print byte counts

          [default: binary]
          [possible values: metric, binary, bytes, gb, gib, mb, mib]
```

**Comment by bootandy** [comment]
Ok, clearly people want this. I'll look into it.

**Comment by bootandy** [comment]
We could merge the --format flag with the --iso flag. - they seem to do similar things.

**Comment by hydrasho** [comment]
I also need this feature. currently i'm forced to use du which is extremely slow and slows down an important script. i wanted to replace it with dust but it forces the -h (human readable). a --format or the inverse of a -h even if it's not precise would be great! thank !

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/pull/373

it's merged it'll be in the next release.

**Comment by sergeevabc** [comment]
@bootandy, every time I run dust.exe on Windows 7 x64 the first thing that appears on the screen is the following line: “This version of Windows does not support ANSI colors”. Not sure why it happens, since, for example, [ripgrep](https://github.com/BurntSushi/ripgrep) and [bat](https://github.com/sharkdp/bat) render colors fine. Anyway, I don't want to feel second-rate here.
