### ISSUE TITLE
Manual page and completions missing in debian package

### ISSUE THREAD

**Issue by johannesst** [bootandy/dust#432]
Hello,

at the moment the debian packages doesn't install the manual page or completion files. 

It would be a nice to have, to get them with the package. 

Best regards, Johannes

**Comment by bootandy** [comment]
Happy to include them. Do you know how ?

**Comment by wugeer** [comment]
@johannesst Hello, I’m happy to tackle this issue.
When I run the command `deb-get install du-dust` on my local Debian virtual machine and install Dust, I indeed don’t find the Dust man pages or any prompt information in bash.
![截图 2024-08-24 22-16-32](https://github.com/user-attachments/assets/f1a284f6-733d-4343-8622-343e8c4a96db)
![截图 2024-08-24 22-17-11](https://github.com/user-attachments/assets/4cdd40d2-5edc-47bb-9aa7-a4d4d3e93434)
![截图 2024-08-24 22-17-45](https://github.com/user-attachments/assets/688b3fcb-10d9-4f9c-8514-adf5411ff839)

From the installation logs, I did not see any information related to configuring man-db.

After adding `man-page` and `completions/dust.bash` configurations under `package.metadata.deb.assets` in `Cargo.toml`, re-packaging with `cargo deb`, and re-installing with `sudo dpkg -i ./target/debian/du-dust_1.1.1-1_amd64.deb`, both `man dust` and the bash prompt for Dust are functioning correctly again.
![image](https://github.com/user-attachments/assets/727e2372-7e7f-471d-af75-89504774790e)
![image](https://github.com/user-attachments/assets/4111d4ac-6460-4c81-9516-6341efd44f3b)
![截图 2024-08-25 09-46-33](https://github.com/user-attachments/assets/3a854f26-d0b3-427c-833b-d8e3579ef531)

For your situation, you can try the modifications I suggested above and then repackage locally and reinstall to see if the issue is resolved. Alternatively, you might wait for the next release of the Debian `du-dust` package to see if the problem is fixed. 
I hope this helps!

**Comment by bootandy** [comment]
Thank you @wugeer
